### ISSUE TITLE
About InstrumentationCallback | Miro's Blog

### ISSUE THREAD

**Issue by MiroKaku** [MiroKaku/Blog#18]
https://mirokaku.github.io/Blog/2019/About-InstrumentationCallback/ 

 分析环境为 x64 版本  InstrumentationCallback 回调的技术刚出来的时候就收藏了, 一直没有去研究学习它. 现在有时间来看一下这个东西. 这个回调存储在 KPROCESS-&gt; InstrumentationCallback. 120: kd&gt; dtx nt!_KPROCESS    [+0x100] InstrumentationCallback : 0x7

**Comment by Asdiopss** [comment]
我这是沙发吗？  米宋大佬牛P~~~~
