### ISSUE TITLE
Windows kernel learning: 3. Memory Management | Miro's Blog

### ISSUE THREAD

**Issue by MiroKaku** [MiroKaku/Blog#7]
https://mirokaku.github.io/Blog/2017/3-Memory-Management/ 

 一个操作系统要称为现代意义上的操作系统就必须提供对内核的保护, 对不同用户程序之间的隔离, 并允许软件的载入位置浮动.而满足这些基本要求的手段, 就是采用基于页面映射的 “虚拟内存” 机制, 或者说提供 “分页内存管理”. 在硬件上, 这是由 CPU 芯片的 “存储管理单元” MMU 支持的. 而在软件商, 则由操作系统内核中的内存管理模块实现.

**Comment by hMihaiDavid** [comment]
This seems like good content. I wish I could understand it!
